server:
  port: 8080

spring:

  mvc:
    servlet:
      path: /api

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 16379
      password: p@123456
      timeout: 60000

  datasource:
    url: jdbc:h2:mem:blog;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/realm-sangkhim
        jwt.jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter.resource-id: client-sangkhim
    converter.principal-attribute: preferred_username

keycloak:
  realm: realm-sangkhim
  auth-server-url: http://localhost:18080/realms/${keycloak.realm}/protocol/openid-connect/token